src/main/java/ca/bcit/info/pms/controller/EmployeeController.java
package ca.bcit.info.pms.controller;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import ca.bcit.info.pms.model.Credential;
import ca.bcit.info.pms.model.Employee;
import ca.bcit.info.pms.model.PayLevel;
import ca.bcit.info.pms.model.PayLevel.PayGrade;
import ca.bcit.info.pms.service.EmployeeService;

@Named( "empController" )
@RequestScoped
public class EmployeeController implements Serializable
{

	@Inject
	private EmployeeService empService;

	@Inject
	private UserController userController;

	/** Hold the new employee information. */
	@Inject
	private Employee employee;

	/** Hold info about new employee's supervisor username from and to form. */
	private String supervisorUsername;

	/**
	 * Hold info about new employee's timesheet approver username from and to
	 * form.
	 */
	private String tsApproverUsername;

	private static final Logger logger = LogManager.getLogger( EmployeeController.class );

	/**
	 * Add new Employee to database.
	 */
	public String addEmployee()
	{
		boolean foundSupervisor = updateEmpSupervisor();
		// return to the form to correct information
		if ( !foundSupervisor )
		{
			return null;
		}

		initializeNewEmployee();

		empService.persistEmployee( employee );
		logger.info( "successfully create new employee: " + employee.toString() );

		return "viewEmployeeHr";
	}

	public String updateEmployee()
	{
		boolean foundSupervisor = updateEmpSupervisor();
		// return to the form to correct information
		if ( !foundSupervisor )
		{
			return null;
		}

		boolean foundApprover = addEmpTimesheetApprover();
		if ( !foundApprover )
		{
			return null;
		}

		empService.updateEmployee(employee);
		logger.info( "successfully updated employee: " + employee.toString() );

		return "viewEmployeeHr";
	}

	private Employee initializeNewEmployee()
	{
		employee.setTimesheetApprover( employee.getSupervisor() );
		employee.setActiveStatus( true );
		employee.setFlexTimeBanked(new BigDecimal(0));
		employee.setVacationBanked(new BigDecimal(0));

		return employee;
	}

	/**
	 * find employee with username = supervisorUsername, and set it as
	 * employee's supervisor.
	 * 
	 * @return if supervisor was found
	 */
	private boolean updateEmpSupervisor()
	{
		if ( supervisorUsername == null || supervisorUsername.isEmpty() )
		{
			return true; // no supervisor assigned, no need to search
		}

		boolean found = false;
		final Employee supervisor = empService.findEmployeeByUsername( supervisorUsername );
		if ( supervisor == null )
		{
			FacesContext.getCurrentInstance().addMessage(
			        "employeeForm:mnSupervisor",
			        new FacesMessage( FacesMessage.SEVERITY_ERROR, "", "No employee found with username: "
			                + supervisorUsername ) );
		} else
		{
			employee.setSupervisor( supervisor );
			found = true;
		}

		return found;
	}

	private boolean addEmpTimesheetApprover()
	{
		boolean found = false;

		if ( tsApproverUsername == null || tsApproverUsername.isEmpty() )
		{
			return true; // no supervisor assigned, no need to search
		} else if ( tsApproverUsername.equals( supervisorUsername ) )
		{
			employee.setTimesheetApprover( employee.getSupervisor() );
			found = true;
		} else
		{
			final Employee approver = empService.findEmployeeByUsername( tsApproverUsername );
			if ( approver == null )
			{
				FacesContext.getCurrentInstance().addMessage(
				        "employeeForm:mnTimesheetApprover",
				        new FacesMessage( FacesMessage.SEVERITY_ERROR, "",
				                "No employee found with username: " + tsApproverUsername ) );
			} else
			{
				employee.setTimesheetApprover( approver );
				found = true;
			}
		}

		return found;
	}

	/**
	 * View an employee profile detail.
	 * 
	 * @param emp
	 *            employee to view
	 * @return navigation view-id
	 */
	public String viewEmployee( final Employee emp )
	{
		employee = emp;
		return "viewEmployee";
	}

	public String viewEmployeeHr( final Employee emp )
	{
		employee = emp;
		return "viewEmployeeHr";
	}

	/**
	 * Edit an employee's profile
	 * 
	 * @param emp
	 *            employee to edit
	 * @return navigation view-id
	 */
	public String editEmployee( final Employee emp )
	{
		employee = emp;
		return "editEmp";
	}

	/**
	 * Edit an employee's profile. NOTE: from viewEmployee.xhtml to edit,
	 * employee object is lost before page hit action method because
	 * requestScoped.
	 * 
	 * @return navigation view-id
	 */
	public String editEmployee()
	{
		employee = empService.findEmployeeById( employee.getId() );
		return "editEmp";
	}

	public String assignTsApprover()
	{
		return assignTsApprover( employee.getId() );
	}

	public String assignTsApprover( final String empId )
	{
		employee = empService.findEmployeeById( empId );

		final Employee approver = employee.getTimesheetApprover();
		if ( approver != null )
		{
			tsApproverUsername = approver.getCredential().getUsername();
		}

		return "assignApprover";
	}

	public String updateTsApprover()
	{
		final boolean found;
		String returnUrl = null;

		employee = empService.findEmployeeById( employee.getId() );
		found = addEmpTimesheetApprover();
		if ( found )
		{
			empService.updateEmployee( employee );
			returnUrl = "viewEmployeeHr";
		}

		return returnUrl;
	}

	public String toggleEmployeeStatus() {
		employee = empService.findEmployeeById(employee.getId());
		if (employee.isActiveStatus()) {
			employee.setActiveStatus(false);
		} else {
			employee.setActiveStatus(true);
		}

		empService.updateEmployee(employee);
		return null;
	}


	public String enableEmployee() {
		employee = empService.findEmployeeById(employee.getId());
		employee.setActiveStatus(true);
		empService.updateEmployee(employee);
		return null;
	}

	public PayGrade [] getPayLevelItems()
	{
		return PayLevel.PayGrade.values();
	}

	public List< Employee > getEmployees()
	{
		return empService.getAllEmployee();
	}

	/**
	 * @return a list of employees managed by this supervisor
	 */
	public List< Employee > getManagedEmployees()
	{
		final String currUserId = userController.getUser().getId();
		return empService.getManagedEmployeeFor(currUserId);
	}

	public Employee getEmployee()
	{
		if ( employee.getCredential() == null )
		{
			employee.setCredential( new Credential() );
		}
		return employee;
	}

	public void setEmployee( Employee employee )
	{
		this.employee = employee;
	}

	public String getSupervisorUsername()
	{
		final Employee supervisor = employee.getSupervisor();
		if ( supervisor != null )
		{
			supervisorUsername = supervisor.getCredential().getUsername();
		}

		return supervisorUsername;
	}

	public void setSupervisorUsername( String username )
	{
		this.supervisorUsername = username;
	}

	public String getTsApproverUsername()
	{
		final Employee approver = employee.getTimesheetApprover();
		if ( approver != null )
		{
			tsApproverUsername = approver.getCredential().getUsername();
		}
		return tsApproverUsername;
	}

	public void setTsApproverUsername( String username )
	{
		this.tsApproverUsername = username;
	}

	public String getEmpAuthorizations()
	{
		final Map< String, Boolean > authMap = empService.checkAuthorization( employee.getId() );
		return empService.getAvailableAuths( authMap );
	}

	public String getFlexTime() {
		final BigDecimal timeBanked = empService.getBankedFlexTime(employee.getId());
		return timeBanked + " hours";
	}

}

src/main/java/ca/bcit/info/pms/controller/UserController.java
package ca.bcit.info.pms.controller;

import ca.bcit.info.pms.model.Credential;
import ca.bcit.info.pms.model.Employee;
import ca.bcit.info.pms.service.EmployeeService;
import ca.bcit.info.pms.service.PasswordHash;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.inject.Inject;
import javax.inject.Named;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Map;
import java.util.Set;
import java.util.StringTokenizer;

@Named( "userController" )
@SessionScoped
public class UserController implements Serializable {

    @Inject
    private EmployeeService empService;

    @Inject
    private Credential credential;

    @Inject
    private Employee user;

    private Map<String, Boolean> authorizations;

    private String newCredential;
    private String currentPassword;
    private String confirmCredential;

    private static final Logger logger = LogManager.getLogger(UserController.class);

    /**
     * Verify login credential.
     * If credential valid, initialize user, check user authorizations.
     * @return navigation view-id
     */
    public String login() {
        final boolean isCorrect = empService.checkCredentials(credential);
        String returnPath;

        if (isCorrect) {
            user = empService.findEmployeeByUsername(credential.getUsername());
            authorizations = empService.checkAuthorization( user.getId() );

            returnPath = "loginSuccess";
            logger.info("Login Success");
        }
        else  {
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                            "Your username and password didn't match. Try again. ", null));
            context.getExternalContext().invalidateSession();

            returnPath = "loginFail";
            logger.info("Login Failed");
        }

        return returnPath;
    }

    /**
     * PreRender event listener, prevent unauthenticated access to pages.
     * If not authenticated, redirect to login page and show error message.
     * @param event
     */
    public void checkAuthentication(ComponentSystemEvent event) {
        FacesContext context = FacesContext.getCurrentInstance();

        if (!isAuthenticated()) {
            context.addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                            "Please login to access the page.", null));

            context.getApplication().getNavigationHandler().
                    handleNavigation(context, null, "unauthenticated");

            logger.info("unauthenticated access");
        }
    }


    /**
     * @return if current user is authenticated (has login).
     */
    private boolean isAuthenticated() {
        boolean isAuthenticated = false;

        if (user != null && user.getId() != null) {
            isAuthenticated = true;
        }

        return isAuthenticated;
    }

    public void checkAuthorization(ComponentSystemEvent event) {
        if(!isAuthenticated()) {
            return; // no need to check HR permission if not authenticated
        }

        final FacesContext ctx = FacesContext.getCurrentInstance();
        final String roles = (String) event.getComponent().getAttributes().get("requiredRoles");

        if (!isAuthorized(roles)) {
            ctx.addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                            "You don't have authorization to access " + ctx.getViewRoot().getViewId(), null));

            ctx.getApplication().getNavigationHandler().
                    handleNavigation(ctx, null, "unauthorized");

            logger.info("unauthorized access to HR functions.");
        }
    }

    public boolean isProjectManagerFor(final String id) {
        boolean isManager = false;

        if (isAuthorized(Employee.ROLE_PROJECT_MANAGER)) {
            isManager = empService.isProjectManagerFor(user.getId(), id);
        }

        return isManager;
    }

    public boolean isAssistantFor(final String id) {
        boolean isAssistant = false;

        if (isAuthorized(Employee.ROLE_ASSISTANT)) {
            isAssistant = empService.isAssistantFor(user.getId(), id);
        }

        return isAssistant;
    }

    public boolean isEngineerFor(final int id) {
        boolean isEngineer = false;

        if (isAuthorized(Employee.ROLE_WP_MANAGER)) {
            logger.info("is Engineer: " + user.getLastName());
            isEngineer = empService.isEngineerFor(user.getId(), id);
        }

        return isEngineer;
    }

    public boolean isSupervisorFor(final String id) {
        boolean isSupervisor = false;

        if (isAuthorized(Employee.ROLE_SUPERVISOR)) {
            isSupervisor=  empService.isSupervisorFor(user.getId(), id);
        }

        return isSupervisor;
    }

    /**
     * @param roles string of roles required for authorization, delimited by comma(,) .
     *              Role name must match ones defined in Employee class
     * @return if current user has required authorization
     */
    public boolean isAuthorized(final String roles) {
        boolean isAuthorized;
        final StringTokenizer tokenizer;
        String role;

        isAuthorized = false;
        tokenizer = new StringTokenizer(roles, ",");

        while (tokenizer.hasMoreTokens()) {
            role = tokenizer.nextToken();
            Boolean hasRole = authorizations.get(role);
            if (hasRole != null && hasRole) {
                isAuthorized = true;
                break;
            }
        }

        return isAuthorized;
    }

    /**
     * End current user session.
     * @return navigation view-id
     */
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "logout";
    }

    /**
     * Change current user's password.
     * @return navigation view-id
     */
    public String changePassword() {
        FacesContext context = FacesContext.getCurrentInstance();
        if (currentPassword.equals(credential.getPassword())) {
            if (newCredential.equals(confirmCredential)) {
                credential.setPassword(newCredential);
                empService.updateCredential(credential);
                credential = new Credential();

                context.addMessage(null,
                        new FacesMessage(FacesMessage.SEVERITY_INFO,
                                "Password changed successfully. Please login again.", null));
            } else {
                context.addMessage("changePassForm:confirmNewPassword",
                        new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error",
                                "Make sure confirm password match your new password."));
            }
        } else {
            context.addMessage("changePassForm:currentPassword",
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error",
                            "You must enter your current password to change your password. This one doesn't match"));

        }

        return null;
    }

    public Employee getUser() {
        return user;
    }

    public void setUser(Employee user) {
        this.user = user;
    }

    public Map<String, Boolean> getAuthorizations() {
        return authorizations;
    }

    public void setAuthorizations(Map<String, Boolean> authorizations) {
        this.authorizations = authorizations;
    }

    public String getAuths() {
        return empService.getAvailableAuths(authorizations);
    }

    public String getCurrentPassword() {
        return currentPassword;
    }

    public void setCurrentPassword(String currentPassword) {
        this.currentPassword = currentPassword;
    }

    public String getNewCredential() {
        return newCredential;
    }

    public void setNewCredential(String newCredential) {
        this.newCredential = newCredential;
    }

    public String getConfirmCredential() {
        return confirmCredential;
    }

    public void setConfirmCredential(String confirmCredential) {
        this.confirmCredential = confirmCredential;
    }

    public Credential getCredential() {
        return credential;
    }

    public void setCredential(Credential credential) {
        this.credential = credential;
    }

    public String getFlexTime() {
        final BigDecimal timeBanked = empService.getBankedFlexTime(user.getId());

        return timeBanked + " hours";
    }
}

src/main/webapp/employee/_viewEmployeePartial.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

<h:head>
    <title></title>
</h:head>
<h:body>
    <ui:composition>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 ">
                <h:form id="employeeForm" styleClass="form-inline">
                    <h:inputHidden value="#{empController.employee.id}"/>

                    <dl class="dl-horizontal">
                        <dt>#{msgs.id}</dt>
                        <dd>#{empController.employee.id}</dd>

                        <dt>#{msgs.userName}</dt>
                        <dd>#{empController.employee.credential.username}</dd>

                        <dt>#{msgs.firstName}</dt>
                        <dd>#{empController.employee.firstName}</dd>

                        <dt>#{msgs.lastName}</dt>
                        <dd>#{empController.employee.lastName}</dd>

                        <dt>#{msgs.email}</dt>
                        <dd>#{empController.employee.email}</dd>

                        <dt>#{msgs.authorizations}</dt>
                        <dd>#{empController.empAuthorizations}</dd>

                        <!-- TODO implement change / assign methods -->
                        <dt>#{msgs.payLevel}</dt>
                        <dd>
                            #{empController.employee.payGrade}
                        </dd>

                        <dt>#{msgs.supervisor}</dt>
                        <dd>
                            #{empController.employee.supervisor.firstName}
                            #{empController.employee.supervisor.lastName}
                        </dd>

                        <dt>#{msgs.timesheetApprover}</dt>
                        <dd>
                            #{empController.employee.timesheetApprover.firstName}
                            #{empController.employee.timesheetApprover.lastName}
                                        <span> [ <h:commandLink action="#{empController.assignTsApprover}"
                                                                value="#{empController.employee.timesheetApprover != null ? 'change' : 'assign' }"/> ]
                                        </span>
                        </dd>

                        <dt>#{msgs.flextime}</dt>
                        <dd>#{empController.flexTime}</dd>

                        <dt>#{msgs.vacation}</dt>
                        <dd>#{empController.employee.vacationBanked}</dd>

                        <dt>#{msgs.emp_status}</dt>
                        <dd>#{empController.employee.activeStatus == true ? 'Active' : 'Disabled'}</dd>
                    </dl>
                </h:form>
            </div>
        </div>

    </ui:composition>
</h:body>
</html>

src/main/webapp/employee/addEmpToProject.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">
		<f:metadata>
			<f:event type="preRenderView"
				listener="#{userController.checkAuthorization}" />
			<f:attribute name="requiredRoles" value="Supervisor" />
		</f:metadata>
		<ui:define name="windowTitle">#{msgs.assignToProject}</ui:define>

		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="employee.css" />
		</ui:define>

		<ui:define name="content">
			<div class="col-xs-12 col-sm-12 col-md-12">

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">

						<div id="breadcrumb">
							<h:form>
								<ol class="breadcrumb">
									<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
									<li><h:commandLink action="viewAllProjects"
											value="#{msgs.viewAllProject}" /></li>
									<li class="active">#{msgs.assignToProject}</li>
								</ol>
							</h:form>
						</div>

						<div id="pageTitle">
							<h1>#{msgs.assignToProject}</h1>
						</div>
						<ui:insert name="notificationArea">
							<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
						</ui:insert>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-4">
						<div class="panel panel-default ">
							<div class="panel-heading">
								<h3 class="panel-title">For Project
									#{projectController.project.name}</h3>
							</div>
							<div class="panel-body">
								<dl class="dl-horizontal">
									<dt>ID</dt>
									<dd>#{projectController.project.id}</dd>
									<dt>Name</dt>
									<dd>#{projectController.project.name}</dd>
									<dt>Description</dt>
									<dd>#{projectController.project.description}</dd>
									<dt>Project Manager</dt>
									<dd>#{projectController.project.projectManager.firstName}
										#{projectController.project.projectManager.lastName}</dd>
									<dt>Employees Assigned</dt>
									<dd>
										<ol>
											<ui:repeat var="assigned"
												value="#{projectController.project.employees.toArray()}">
												<li>#{assigned.firstName} #{assigned.lastName}</li>
											</ui:repeat>
										</ol>
									</dd>
								</dl>
							</div>
						</div>
					</div>
					<!-- /col -->
				</div>
				<!-- /outter row -->

				<div class="row">
					<div class="container">
						<h3>Select Employees to Assign</h3>
						<h:form>
							<h:inputHidden value="#{projectController.project.id}" />

							<p:dataTable id="empTable" styleClass="bg-none table"
								var="employee" value="#{empController.managedEmployees}">
								<!--c:if employee isn't already assigned-->
								<p:column headerText="#{msgs.id}">
									<h:outputText class="paddingHalf" value="#{employee.id}" />
								</p:column>

								<p:column headerText="#{msgs.userName}">
									<h:outputText class="paddingHalf" value="#{employee.credential.username}" />
								</p:column>

								<p:column headerText="#{msgs.firstName}">
									<h:outputText class="paddingHalf" value="#{employee.firstName}" />
								</p:column>

								<p:column headerText="#{msgs.lastName}">
									<h:outputText class="paddingHalf" value="#{employee.lastName}" />
								</p:column>

								<p:column headerText="#{msgs.payLevel}">
									<h:outputText class="paddingHalf" value="#{employee.payGrade}" />
								</p:column>
								<p:column>
									<h:commandLink value="Assign"
										action="#{projectController.insertEmpToProject(employee)}" />
								</p:column>
							</p:dataTable>


						</h:form>
					</div>
				</div>

			</div>
			<!-- /col -->
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/employee/profile.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">

		<ui:define name="windowTitle">#{msgs.profile}</ui:define>

		<ui:define name="additionalStyleSheets">
		</ui:define>



		<ui:define name="content">
			<!-- change the value if using left menu -->
			<div class="col-md-12">

				<div class="container-fluid" id="content">

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">

							<div id="breadcrumb">
							<h:form>
								<ol class="breadcrumb">								
								<li><h:commandLink action="mypage" value="#{msgs.myPage}"/></li>									
									<li class="active">#{msgs.profile}</li>
								</ol>
								</h:form>
							</div>

							<div id="pageTitle">
								<h1>#{msgs.profile}</h1>
							</div>
							<ui:insert name="notificationArea">
								<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
							</ui:insert>
						</div>
					</div>

					<div class="row">

						<div class="col-xs-12 col-sm-12 col-md-6">
                            <dl class="dl-horizontal">
                                <dt>#{msgs.id}</dt>
                                <dd>#{userController.user.id}</dd>

                                <dt>#{msgs.userName}</dt>
                                <dd>#{userController.user.credential.username}</dd>

                                <dt>#{msgs.firstName}</dt>
                                <dd>#{userController.user.firstName}</dd>

                                <dt>#{msgs.lastName}</dt>
                                <dd>#{userController.user.lastName}</dd>

                                <dt>#{msgs.email}</dt>
                                <dd>#{userController.user.email}</dd>

                                <dt>#{msgs.authorizations}</dt>
                                <dd>#{userController.auths}</dd>

                                <dt>#{msgs.payLevel}</dt>
                                <dd>#{userController.user.payGrade}</dd>

                                <dt>#{msgs.supervisor}</dt>
                                <dd>#{userController.user.supervisor.firstName} #{userController.user.supervisor.lastName}</dd>

                                <dt>#{msgs.timesheetApprover}</dt>
                                <dd>#{userController.user.timesheetApprover.firstName} #{userController.user.timesheetApprover.lastName}</dd>

                                <dt>#{msgs.flextime}</dt>
                                <dd>#{userController.flexTime}</dd>

                                <dt>#{msgs.vacation}</dt>
                                <dd>#{userController.user.vacationBanked}</dd>
                            </dl>
						</div><!-- /col -->
						
						
					</div><!-- /row -->		
				</div><!-- /container -->
			</div><!-- /col -->
		</ui:define>
		<!-- end of wrapper -->
	</ui:composition>
</h:body>
<!-- end of body -->
</html>

src/main/webapp/employee/viewEmployee.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">
	<f:metadata>
		<f:event type="preRenderView"
			listener="#{userController.checkAuthorization}" />
		<f:attribute name="requiredRoles" value="Supervisor" />
	</f:metadata>
		<ui:define name="windowTitle">#{msgs.employees}</ui:define>
		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="viewAllEmployees.css" />
		</ui:define>
		<ui:define name="content">
			<div id="content">
				<div class="col-xs-12 col-sm-12 colmd-12">


					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">

							<div id="breadcrumb">
								<h:form>
									<ol class="breadcrumb">
										<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
                                            <li><h:commandLink action="viewManagedEmp"
                                                               value="#{msgs.manageEmployees}" /></li>
										<li class="active">#{msgs.viewEmployee}</li>
									</ol>
								</h:form>
							</div>

							<div id="pageTitle">
								<h1>#{msgs.viewEmployee}</h1>
							</div>
							<ui:insert name="notificationArea">
								<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
							</ui:insert>
						</div>
					</div>

                    <ui:insert name="disaplyTimesheet">
                        <ui:include src="_viewEmployeePartial.xhtml" />
                    </ui:insert>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>