src/main/java/ca/bcit/info/pms/controller/ProjectController.java
package ca.bcit.info.pms.controller;

import ca.bcit.info.pms.model.Employee;
import ca.bcit.info.pms.model.Project;
import ca.bcit.info.pms.model.ProjectStatus;
import ca.bcit.info.pms.model.RateSheet;
import ca.bcit.info.pms.model.WorkPackage;
import ca.bcit.info.pms.service.EmployeeService;
import ca.bcit.info.pms.service.ProjectService;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import java.io.Serializable;
import java.util.List;

@Named("projectController")
@ConversationScoped
public class ProjectController implements Serializable {

	@Inject
	private ProjectService projService;

	@Inject
	private UserController userController;

	@Inject
	private EmployeeController employeeController;

	@Inject
	private EmployeeService empService;

	@Inject
	private Conversation conversation;

	@Inject
	private Project project;

	/** keeps track of new project manager's id. */
	private String managerId;

	private static final Logger logger = LogManager
			.getLogger(ProjectController.class);
	
	private java.util.Date startDate, endDate;
	
	private String assistantUsername;

	public java.util.Date getStartDate() {
		return startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.util.Date getEndDate() {
		return endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	private void beginConversation() {
		if (conversation.isTransient()) {
			logger.info("Project, begin conversation.");
			conversation.begin();
		}
	}

	private void endConversation() {
		if (!conversation.isTransient()) {
			logger.info("Project, end conversation.");
			conversation.end();
		}
	}

	/**
	 * @return the project
	 */
	public Project getProject() {
		if (project.getProjectManager() == null) {
			final Employee manager = userController.getUser();
			project.setProjectManager(manager);
		}

		return project;
	}

	/**
	 * @param project
	 *            the project to set
	 */
	public void setProject(Project project) {
		this.project = project;
	}

	public String addProject() {

		if (project == null)
			return null;

		if (this.startDate.after(this.endDate)) {
			FacesContext.getCurrentInstance().addMessage(
					"newProjectForm:popupEndDate",
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "",
							"EndDate must be after StartDate"));
			return null;
		}

		Project backProject = projService.getProject(project.getId());
		if (backProject != null) {
			FacesContext.getCurrentInstance().addMessage(
					"newProjectForm:itProjectNumber",
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "",
							"Project already exist!: " + project.getId()));
			return null;
		}

		project.setStartDate(convertJavaDateToSqlDate(startDate));
		project.setEndDate(convertJavaDateToSqlDate(endDate));
		projService.persistProject(project);
		logger.info("successfully create new project: " + project.toString());

		beginConversation();
		return "viewProjectDetails";
	}

	/**
	 * Update a project's manager.
	 * 
	 * @return
	 */
	public String updateProjectManager() {
		project = projService.getProject(project.getId());

		final Employee newManager = empService.findEmployeeById(managerId);
		project.setProjectManager(newManager);

		projService.updateProject(project);
		return "viewProjectDetails";
	}

	public String updateAssistant() {
		project = projService.getProject(project.getId());

		final Employee assistant = empService
				.findEmployeeByUsername(assistantUsername);
		if (assistant == null) {
			FacesContext.getCurrentInstance().addMessage(
					"projectForm:mnAssistant",
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "",
							"No employee found with username: "
									+ assistantUsername));

			return null;
		}

		project.setAssistant(assistant);
		projService.updateProject(project);

		return "viewProjectDetails";
	}

	public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
		return new java.sql.Date(date.getTime());
	}

	public List<Project> getProjects() {
		return projService.getAllProjects();
	}

	public String getManagerId() {
		return managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}


	/**
	 * @return a list of projects managed by current user.
	 */
	public List<Project> getManagedProjects() {
		List<Project> managedProjects;
		final String userId = userController.getUser().getId();

		final boolean isManager = userController
				.isAuthorized(Employee.ROLE_PROJECT_MANAGER);
		final boolean isAssistant = userController
				.isAuthorized(Employee.ROLE_ASSISTANT);
		if (isManager && isAssistant) {
			final List<Project> assistantList = projService
					.getAssistedProjectsFor(userId);
			managedProjects = projService.getManagedProjectsFor(userId);
			managedProjects.addAll(assistantList);
		} else if (isManager) {
			managedProjects = projService.getManagedProjectsFor(userId);

		} else {
			managedProjects = projService.getAssistedProjectsFor(userId);
		}

		return managedProjects;
	}

	/**
	 * @return a list of possible employee to be assigned as project manager.
	 */
	public List<Employee> getProjectManagerCandidates() {
		final List<Employee> candidates = employeeController
				.getManagedEmployees();
		final Employee currentManager = project.getProjectManager();
		final Employee currentUser = userController.getUser();

		// allow current manager as a choice
		if (!candidates.contains(currentManager)) {
			candidates.add(currentManager);
		}

		// allow supervisor to assign himself as manager
		if (!candidates.contains(currentUser)) {
			candidates.add(currentUser);
		}

		candidates.sort((o1, o2) -> o1.getLastName()
				.compareTo(o2.getLastName()));

		return candidates;
	}
	
	public List<Employee> getProjectEmployees() {
		   return projService.getAssignedEmployee(project.getId());
	}

	/**
	 * @return a list of the top level work packages for this project
	 */
	public List<WorkPackage> getTopLevelPackages() {
		return projService.getTopLevelPackages(project.getId());
	}

	/**
	 * 
	 * @return
	 */
	public String goEditProject() {
		this.project = projService.getProject(project.getId());
		if(project == null) return null;
		if (project.getStartDate() != null)
			startDate = new java.util.Date(project.getStartDate().getTime());
		if (project.getEndDate() != null)
			endDate = new java.util.Date(project.getEndDate().getTime());
		if(project.getRateSheet() == null)
			project.setRateSheet(new RateSheet());
		return "editProject";
	}

	public void clearFields() {

	}

	/**
	 * Route to assign employee to project page.
	 * 
	 * @return navigating route.
	 */
	public String assignToProject(final Project proj) {
		project = proj;
		return "addEmpToProject";
	}

	/**
	 * Assign employee to project and update project in database.
	 * 
	 * @param emp
	 *            employee to assign.
	 * @return navigating route.
	 */
	public String insertEmpToProject(final Employee emp) {
		project = projService.getProject(project.getId());
		project.assignEmployee(emp);

		projService.updateProject(project);
		return null;
	}

	/**
	 * 
	 * @return
	 */
	public String viewProjectDetails(final Project project) {
		beginConversation();
		this.project = project;
		return "viewProjectDetails";
	}

	public String goViewProject(final String id) {
		beginConversation();
		this.project = projService.getProject(id);
		return "viewProjectDetails";
	}

	/**
	 * 
	 * @return
	 */
	public String updateProject() {
		if (this.startDate.after(this.endDate)) {
			FacesContext.getCurrentInstance().addMessage(
					"editProjectForm:popupEndDate",
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "",
							"EndDate must be after StartDate"));
			return null;
		}

		project.setStartDate(convertJavaDateToSqlDate(startDate));
		project.setEndDate(convertJavaDateToSqlDate(endDate));
		projService.updateProject(project);
		return "viewProjectDetails";
	}

	public String changeManager() {
		project = projService.getProject(project.getId());
		return "changeProjectManager";
	}

	public String changeAssistant() {
		project = projService.getProject(project.getId());
		return "changeAssistant";
	}

	public String goCreateProject() {
		endConversation();
		return "newProject";
	}

	public void setAssistantUsername(String assistantUsername) {
		this.assistantUsername = assistantUsername;
	}

	public String getAssistantUsername() {
		return assistantUsername;
	}

	public ProjectStatus[] getStatuses() {
		return ProjectStatus.values();
	}

}

src/main/java/ca/bcit/info/pms/controller/WorkPackageController.java
/**
 * 
 */
package ca.bcit.info.pms.controller;

import ca.bcit.info.pms.model.Budget;
import ca.bcit.info.pms.model.Employee;
import ca.bcit.info.pms.model.EngineerBudget;
import ca.bcit.info.pms.model.Project;
import ca.bcit.info.pms.model.ProjectStatus;
import ca.bcit.info.pms.model.WorkPackage;
import ca.bcit.info.pms.service.EmployeeService;
import ca.bcit.info.pms.service.ProjectService;
import ca.bcit.info.pms.service.WorkPackageService;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.inject.Inject;
import javax.inject.Named;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 *
 */

@Named( "workPackageController" )
@ConversationScoped
public class WorkPackageController implements Serializable
{

	@Inject
	private WorkPackage workPackage;

	@Inject
	private WorkPackageService workPackageService;

	@Inject
	private ProjectService projectService;

	@Inject
	private EmployeeService employeeService;
	
	@Inject
	private UserController userController;

	@Inject
	private Conversation conversation;
	
	private Employee employee;

	private String reId;

	private Integer parentWPId;
	

	private static final Logger logger = LogManager.getLogger( WorkPackageController.class );


	private void beginConversation() {
		logger.info("attempt start wp conversation...");
		if (conversation.isTransient()) {
			logger.info("Work Package, begin conversation.");
			conversation.begin();
		}
	}

	private void endConversation() {
		if(!conversation.isTransient()){
			logger.info("Work Package, end conversation.");
			conversation.end();
		}
	}

	

	public  ProjectStatus[] getStatuses()
	{			
		return ProjectStatus.values();
	}

	public String addWorkPackage()
	{
		logger.info("Entered add work package");
		if(workPackage == null) 
			return null;
		
		logger.info("Work Package is not null");

		WorkPackage workPackages = workPackageService.getUniquePackage(workPackage.getProject().getId(), workPackage.getPackageNum());
    	if(workPackages != null){
    		FacesContext.getCurrentInstance().addMessage( "newWorkPackageForm:itWorkPackageNumber",
                    new FacesMessage( FacesMessage.SEVERITY_ERROR, "", "Work Package is not unique with combinition of Project ID and Package Number!: "
                            + workPackage.getPackageNum() ) );
    		return null;
    	}
		
    	Employee employee = employeeService.findEmployeeById(reId);
    	if(employee == null){
    		FacesContext.getCurrentInstance().addMessage( "newWorkPackageForm:mnSupervisor",
                    new FacesMessage( FacesMessage.SEVERITY_ERROR, "", "Employee does not exist!: "
                            + reId ) );
    		return null;
    	}
    	
		WorkPackage parentWP = null;
		
		if ( parentWPId != null ) {
			parentWP = workPackageService.findWorkPackageById(parentWPId);
		}
		
		logger.info("Attempting to save workpackage");
		
		workPackage.setParentWP(parentWP);
		workPackage.setEmployee(employee);
		workPackageService.persistWorkPackage( workPackage );
		
		logger.info( "successfully create new WorkPackage: " + workPackage.toString() );

		beginConversation();
		return "viewWorkPackageDetails";
	}

	public WorkPackage getWorkPackage()
	{
		if (workPackage != null) {
			if (workPackage.getParentWP() == null) {
				workPackage.setParentWP(new WorkPackage());
			}
			if (workPackage.getEmployee() == null) {
				workPackage.setEmployee(new Employee());
			}
		}

		return workPackage;
	}

	public void setWorkPackage( WorkPackage workPackage )
	{
		this.workPackage = workPackage;
	}

	public List< WorkPackage > getWorkPackages()
	{
		return workPackageService.getAllWorkPackages();
	}

	public String goEditPackage(String id)
	{
		workPackage = workPackageService.findWorkPackageById(Integer.valueOf(id));
		if(workPackage.getBudget()==null)
			workPackage.setBudget(new Budget());
			//workPackage.getBudget().setId(workPackage.getId());
			//System.out.println("Budget id: " + workPackage.getBudget().getId());
		if(workPackage.getEngineerBudget()==null)
			workPackage.setEngineerBudget(new EngineerBudget());
			//workPackage.getEngineerBudget().setId(workPackage.getId());
			//System.out.println("Engineer Budget id: " + workPackage.getEngineerBudget().getId());

		if(workPackage!=null && workPackage.getParentWP() != null)
			parentWPId = workPackage.getParentWP().getId();
		return "editWorkPackage";
	}

	public String goNewTopLevelPackage( Project project )
	{
		workPackage.setProject( project );
		return "newWorkPackage";
	}

	/**
	 * Go to create new work package. Similar to goNewTopLevelPackage
	 * but takes project id rather than the project object.
	 * @param projId project id
	 * @return navigation view id
	 */
	public String goCreatePackage( final String projId )
	{
		workPackage = new WorkPackage();
		final Project project = projectService.getProject( projId );
		workPackage.setProject( project );

		return "newWorkPackage";
	}

	public String goChildPackage( WorkPackage parentWorkPackage )
	{
		beginConversation();
		workPackage = new WorkPackage();
		Project project = projectService.getProject(parentWorkPackage.getProject().getId());
		workPackage.setProject( project );
		workPackage.setEmployee(new Employee());
		parentWPId = parentWorkPackage.getId();
		
		return "newWorkPackage";
	}

	/**
	 * @return a list of all work packages an employee is assigned to.
	 */
	public List< WorkPackage > getMyWorkPackages()
	{
		final String userId = userController.getUser().getId();
		return workPackageService.findAssignedWorkPackages( userId );
	}

	/**
	 * @return a list of leaf work packages an employee is assigned to.
	 */
	public List<WorkPackage> getMyLeafWorkPackages() {
	    List<WorkPackage> leafPackages = new ArrayList<WorkPackage>();
	    
	    for(WorkPackage wp : getMyWorkPackages()) {
	        if (wp.isLeaf()) {
	            leafPackages.add(wp);
	        }
	    }
	    
	    return leafPackages;
	}
	
	/**
	 * @return a list of projects managed by current user.
	 */
	public List<WorkPackage> getAssociatedWorkPackages() {
		List<WorkPackage> workPackageList = null;
		final String userId = userController.getUser().getId();
		workPackageList = workPackageService.findResponsibleWorkPackages(userId);

		return workPackageList;
	}
	
	public List<Employee> getEmployees() {
		return workPackageService.getAssignedEmployeesToWp(workPackage.getId());
	}
	
	public List<Employee> getAvailableEmployees() {
		return workPackageService.getAssignedEmployeesToProjectNotWp(workPackage.getId(), workPackage.getProject().getId());
	}
	
	public String assignToProject() {
		return "addEmpToWorkPackage";
	}

	
	public List<WorkPackage> getChildWorkPackages() {
		return workPackageService.getChildWorkPackages(workPackage);
	}

	public Integer getParentWPId()
	{
		return parentWPId;
	}

	public void setParentWPId( Integer parentWPId )
	{
		this.parentWPId = parentWPId;
	}

	public void setBooleanLeaf( AjaxBehaviorEvent event )
	{
		workPackage.setLeaf( workPackage.isLeaf() );
	}

	/**
	 * 
	 * @return
	 */
	public String viewWorkPackageDetails( final WorkPackage workPackage )
	{
		beginConversation();
		this.workPackage = workPackage;
		return "viewWorkPackageDetails";
	}

	public String updateWorkpackage(){		
		WorkPackage parentWP = null;
		//logger.info( parentWPId );
		if ( parentWPId != null )
			parentWP = workPackageService.findWorkPackageById( parentWPId );

		workPackage.setParentWP( parentWP );

		String engineerId = reId;
		if (engineerId == null) {
			engineerId = workPackage.getEmployee().getId();
		}
		Employee employee = employeeService.findEmployeeById(engineerId);
		if(employee == null){
			FacesContext.getCurrentInstance().addMessage( "newWorkPackageForm:mnSupervisor",
					new FacesMessage( FacesMessage.SEVERITY_ERROR, "", "Employee does not exist!: "
							+ reId ) );
			return null;
		}

		workPackage.setEmployee(employee);

		workPackageService.updateWorkPackage(workPackage);
		workPackage = workPackageService.findWorkPackageById(workPackage.getId());
		//engineerBudgetMngr.merge(engBudget);
		return "viewWorkPackageDetails";
	}
	
	/**
	 * Assign employee to project and update project in database.
	 * 
	 * @param emp
	 *            employee to assign.
	 * @return navigating route.
	 */
	public String insertEmpToWp(final Employee emp) {
		workPackage = workPackageService.findWorkPackageById(workPackage.getId());
		workPackage.assignEmployee(emp);

		workPackageService.updateWorkPackage(workPackage);
		return null;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getReId() {
		return reId;
	}

	public void setReId(String reId) {
		this.reId = reId;
	}

}

src/main/webapp/projects/addEmpToWorkPackage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">
		<f:metadata>
			<f:event type="preRenderView"
				listener="#{userController.checkAuthorization}" />
			<f:attribute name="requiredRoles" value="ProjectManager" />
		</f:metadata>
		<ui:define name="windowTitle">#{msgs.assignToWp}</ui:define>

		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="employee.css" />
		</ui:define>

		<ui:define name="content">
			<div class="col-xs-12 col-sm-12 col-md-12">

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">

						<div id="breadcrumb">
							<h:form>
								<ol class="breadcrumb">
									<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
									<li><h:commandLink action="viewWorkPackageDetails"
											value="#{msgs.viewPackageDetails}" /></li>
									<li class="active">#{msgs.assignToWp}</li>
								</ol>
							</h:form>
						</div>

						<div id="pageTitle">
							<h1>#{msgs.assignToWp}</h1>
						</div>
						<ui:insert name="notificationArea">
							<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
						</ui:insert>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-4">
						<div class="panel panel-default ">
							<div class="panel-heading">
								<h3 class="panel-title">For Work Package
									#{workPackageController.workPackage.name}</h3>
							</div>
							<div class="panel-body">
								<dl class="dl-horizontal">
									<dt>ID</dt>
									<dd>#{workPackageController.workPackage.id}</dd>
									<dt>Name</dt>
									<dd>#{workPackageController.workPackage.name}</dd>
									<dt>Description</dt>
									<dd>#{workPackageController.workPackage.description}</dd>
									<dt>Responsible Engineer</dt>
									<dd>#{workPackageController.workPackage.employee.firstName}
										#{workPackageController.workPackage.employee.lastName}</dd>
									<dt>Employees Assigned</dt>
									<dd>
										<ol>
											<ui:repeat var="assigned"
												value="#{workPackageController.employees}">
												<li>#{assigned.firstName} #{assigned.lastName}</li>
											</ui:repeat>
										</ol>
									</dd>
								</dl>
							</div>
						</div>
					</div>
					<!-- /col -->
				</div>
				<!-- /outter row -->

				<div class="row">
					<div class="container">
						<h3>Select Employees to Assign</h3>
						<h:form>
							<h:inputHidden value="#{workPackageController.workPackage.id}" />

							<p:dataTable id="empTable" styleClass="bg-none table"
								var="employee" value="#{workPackageController.availableEmployees}">
								<!--c:if employee isn't already assigned-->
								<p:column headerText="#{msgs.id}">
									<h:outputText value="#{employee.id}" />
								</p:column>

								<p:column headerText="#{msgs.userName}">
									<h:outputText value="#{employee.credential.username}" />
								</p:column>

								<p:column headerText="#{msgs.firstName}">
									<h:outputText value="#{employee.firstName}" />
								</p:column>

								<p:column headerText="#{msgs.lastName}">
									<h:outputText value="#{employee.lastName}" />
								</p:column>

								<p:column headerText="#{msgs.payLevel}">
									<h:outputText value="#{employee.payGrade}" />
								</p:column>
								<p:column>
									<h:commandLink value="Assign"
										action="#{workPackageController.insertEmpToWp(employee)}" />
								</p:column>
							</p:dataTable>


						</h:form>
					</div>
				</div>

			</div>
			<!-- /col -->
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/projects/changeProjectManager.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">

		<ui:define name="windowTitle">#{msgs.changeManager}</ui:define>

		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="project.css" />
		</ui:define>

		<ui:define name="content">
			<div class="col-xs-12 col-sm-12 col-md-12">

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">

						<div id="breadcrumb">
							<h:form>
								<ol class="breadcrumb">
                                    <li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
									<li><h:commandLink action="viewAllProjects" value="#{msgs.viewAllProject}" /></li>
									<li class="active">#{msgs.changeManager}</li>
								</ol>
							</h:form>
						</div>

						<div id="pageTitle">
							<h1>#{msgs.changeManager}</h1>
						</div>
						<ui:insert name="notificationArea">
							<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
						</ui:insert>
					</div>
				</div>

				<div class="row">
                    <div class="col-sm-4">
                        <div class="panel panel-default ">
                            <div class="panel-heading">
                                <h3 class="panel-title">For Project #{projectController.project.name}</h3>
                            </div>
                            <div class="panel-body">
                                <h:form id="projectForm">
                                    <h:inputHidden value="#{projectController.project.id}" />
                                    <div class="form-group">
                                        <h:selectOneMenu id="projectManager" styleClass="form-control" required="true"
														 value="#{projectController.managerId}" >
											<f:selectItems value="#{projectController.projectManagerCandidates}"
														   var="employee" itemValue="#{employee.id}"
														   itemLabel="#{employee.firstName} #{employee.lastName}" />
										</h:selectOneMenu>
									</div>
									<h:commandLink styleClass="btn btn-default" value="#{msgs.save}"
                                                           action="#{projectController.updateProjectManager}" />

                                    <h:message errorClass="text-danger" for=""/>
                                </h:form>
                            </div>
                        </div>
                    </div><!-- /col -->
				</div><!-- /outter row -->
			</div><!-- /col -->
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/projects/searchResultProject.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:composite="http://java.sun.com/jsf/composite"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui">
<head>
<title></title>
</head>
<body>

<ui:composition template="/templatesBootstrap/masterLayout.xhtml">

	<ui:define name="windowTitle">#{msgs.search}</ui:define>

	<ui:define name="content">
		<div class="col-md-12">
			<div class="container-fluid" id="content">

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">

						<div id="breadcrumb">
							<h:form>
								<ol class="breadcrumb">
									<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
									<li class="active">#{msgs.search}</li>
								</ol>
							</h:form>
						</div>

						<div id="pageTitle">
							<h1>#{msgs.project} #{msgs.results}</h1>
						</div>
						<ui:insert name="notificationArea">
							<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
						</ui:insert>
					</div>
				</div>

				<div class="row">

				<div class="col-xs-12 col-sm-12 col-md-6">
							<p:dataTable var="" value="">
								<p:column headerText="#{msgs.projectNumber}">
									<h:outputText value=""/>
								</p:column>
								<p:column headerText="#{msgs.projectName}">
									<h:outputText value=""/>
								</p:column>
								<p:column headerText="#{msgs.projectDescription}">
									<h:outputText value=""/>
								</p:column>								
							</p:dataTable>						
						</div>







				</div>
				<!-- /row of content -->
			</div>
			<!-- /container -->
		</div>
		<!-- /col -->
	</ui:define>
	</ui:composition>
</body>
</html>