src/main/java/ca/bcit/info/pms/model/TimesheetRow.java
package ca.bcit.info.pms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Timesheet row for each work package of a timesheet.
 */
@Entity
public class TimesheetRow implements Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "timesheetrowID", updatable = false, nullable = false)
	private int id;

	@ManyToOne
	@JoinColumn(name = "packageID", nullable = false)
    @NotNull(message = "timesheetRow must have a package number")
    private WorkPackage workPackage;

	private String notes;

    @Column(name = "saturday")
    private BigDecimal saturdayHour;

    @Column(name = "sunday")
	private BigDecimal sundayHour;

	@Column(name = "monday")
	private BigDecimal mondayHour;
	
	@Column(name = "tuesday")
	private BigDecimal tuesdayHour;
	
	@Column(name = "wednesday")
	private BigDecimal wednesdayHour;
	
	@Column(name = "thursday")
	private BigDecimal thursdayHour;
	
	@Column(name = "friday")
	private BigDecimal fridayHour;
	
    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

	public WorkPackage getWorkPackage() {
		return workPackage;
	}

	public void setWorkPackage(WorkPackage workPackage) {
		this.workPackage = workPackage;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public double getSaturdayHour() {
		return saturdayHour.doubleValue();
	}

	public void setSaturdayHour(double sat) {
		this.saturdayHour = new BigDecimal(sat).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public double getSundayHour() {
		return sundayHour.doubleValue();
	}

	public void setSundayHour(double sun) {
		this.sundayHour = new BigDecimal(sun).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public double getMondayHour() {
		return mondayHour.doubleValue();
	}

	public void setMondayHour(double mon) {
		this.mondayHour = new BigDecimal(mon).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public double getTuesdayHour() {
		return tuesdayHour.doubleValue();
	}

	public void setTuesdayHour(double tue) {
		this.tuesdayHour = new BigDecimal(tue).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public double getWednesdayHour() {
		return wednesdayHour.doubleValue();
	}

	public void setWednesdayHour(double wed) {
		this.wednesdayHour = new BigDecimal(wed).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public double getThursdayHour() {
		return thursdayHour.doubleValue();
	}

	public void setThursdayHour(double thur) {
		this.thursdayHour = new BigDecimal(thur).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public double getFridayHour() {
		return fridayHour.doubleValue();
	}

	public void setFridayHour(double fri) {
		this.fridayHour = new BigDecimal(fri).setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	@Transient
	public double getTotalHours() {
		double total;
		try {
			total = fridayHour.add(saturdayHour.add(sundayHour.add(
					mondayHour.add(tuesdayHour.add(wednesdayHour.add(
							thursdayHour)))))).doubleValue();
		} catch (Exception ex) {
			total = 0;
		}
		return total;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof TimesheetRow)) {
			return false;
		}
		TimesheetRow other = (TimesheetRow) obj;
		if (id >= 0) {
			if (id != other.id) {
				return false;
			}
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id < 0) ? 0 : (id + "").hashCode());
		return result;
	}

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("TimesheetRow{");
        sb.append("id=").append(id);
		if (workPackage != null && workPackage.getProject() != null) {
			sb.append(", workPackage=")
					.append(workPackage.getProject().getId()).append("-")
					.append(workPackage.getPackageNum());
		}
        sb.append(", saturdayHour=").append(saturdayHour);
        sb.append(", sundayHour=").append(sundayHour);
        sb.append(", mondayHour=").append(mondayHour);
        sb.append(", tuesdayHour=").append(tuesdayHour);
        sb.append(", wednesdayHour=").append(wednesdayHour);
        sb.append(", thursdayHour=").append(thursdayHour);
        sb.append(", fridayHour=").append(fridayHour);
        sb.append(", notes='").append(notes).append('\'');
        sb.append('}');
        return sb.toString();
    }
    
    
}

src/main/java/ca/bcit/info/pms/controller/EditTimesheetController.java
package ca.bcit.info.pms.controller;

import java.io.Serializable;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Level;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import ca.bcit.info.pms.access.SignatureManager;
import ca.bcit.info.pms.model.Employee;
import ca.bcit.info.pms.model.SignatureObject;
import ca.bcit.info.pms.model.Timesheet;
import ca.bcit.info.pms.model.TimesheetRow;
import ca.bcit.info.pms.model.WorkPackage;
import ca.bcit.info.pms.service.TimesheetService;
import ca.bcit.info.pms.service.WorkPackageService;

@Named( "editTimesheetController" )
@SessionScoped
public class EditTimesheetController implements Serializable {
    private static final Logger logger 
        = LogManager.getLogger(EditTimesheetController.class);

    @Inject
    private Timesheet timesheet;

    @Inject
    private TimesheetService timeService;

    @Inject
    private UserController userController;

    @Inject
    private TimesheetController timesheetController;
    
    @Inject
    private WorkPackageService wpService;

    @Inject
    private SignatureManager signatureManager;
    
    @Inject private SignatureObject sigObject;
    
    boolean isValid = true;

    /**
     * @return Return timesheet
     */
    public Timesheet getTimesheet(){
        return timesheet;
    }

    public void addTimesheetRow() {
        List<TimesheetRow> tsRows = timesheet.getTimesheetRows();
        tsRows.add(newTimesheetRow());
        timesheet.setTimesheetRows(tsRows);
    }

    public TimesheetRow newTimesheetRow() {
        TimesheetRow tsr = new TimesheetRow();
        WorkPackage wp = new WorkPackage();
        tsr.setWorkPackage(wp);
        tsr.setFridayHour(0);
        tsr.setSaturdayHour(0);
        tsr.setSundayHour(0);
        tsr.setMondayHour(0);
        tsr.setTuesdayHour(0);
        tsr.setWednesdayHour(0);
        tsr.setThursdayHour(0);
        return tsr;
    }
    /**
     * Populates timesheet data-member for current user.
     * 
     * @return navigation string
     */
    public String fillThisWeek() {
        Employee user = userController.getUser();
        timesheet = timeService.getCurrentTimesheet(user);

        // if timeheet already submitted.
        if ((timesheet.getSubmitted() != null) && (timesheet.getSubmitted() == true)) {

            timesheetController.viewTimesheet(timesheet);
            return "/timesheets/viewTimesheet";
        }

        return "currentTimesheet";
    }

    public String fillSheetToCorrect(final Timesheet ts) {
        timesheet = ts;

        return "currentTimesheet";
    }

    /**
     * @param timesheet the timesheet to set
     */
    public void setTimesheet(Timesheet timesheet) {
        this.timesheet = timesheet;
    }

    public String addTimesheet(){
        //set functions
        //persist timesheet
        return "newTimesheet";
    }

    public List<Timesheet> getTsApproverPendingList() {
        final String currUserid = userController.getUser().getId();
        return timeService.getApproverPendingTimesheets(currUserid);
    }
    
    public void populateWorkPackage(TimesheetRow tsr) {
        WorkPackage wp = wpService.findWorkPackageById(tsr.getWorkPackage().getId());
        tsr.setWorkPackage(wp);
    }

    /**
     * Persists the timesheet, or sets error message
     * if the timesheet is not valid.
     * @return
     */
    public String saveTimesheet() {
    	isValid = true;
        FacesMessage msg = null;
        List<TimesheetRow> rows = removeEmptyRows(timesheet.getTimesheetRows());
        timesheet.setTimesheetRows(rows);
        
        // A user CAN save an empty timesheet
        if(rows.size() == 0) {
            timeService.updateTimesheet(timesheet);
            return null;
        }
        
        try {
        	if((timesheet.getSubmitted()) == true && (signatureManager.find(timesheet.getId()) != null)) {
                isValid = false;
                msg = new FacesMessage("Already signed and submitted timesheet. Cannot edit");
            }
        } catch (NullPointerException e) {
        	
        }

        if(!noWorkPackagesAreNull(rows) && isValid) {
            isValid = false;
            msg = new FacesMessage("Each row must be associated with a work package");
        }

        if (!dayTotalsAreValid(rows) && isValid){
            isValid = false;
            msg = new FacesMessage("Total hours on individual day cannot exceed 24.00 hours");
        }

        if (!rowWorkPackagesAreUnique(rows) && isValid) {
            isValid = false;
            msg = new FacesMessage("Work Packages must be unique among rows");
        }

        
        if( !sheetTotalsLessThanForty() ) {
        	isValid = false;
            return null;
        }
        

        if(isValid){
        	System.out.println("Saving timesheet: " + timesheet);
            timeService.updateTimesheet(timesheet);
        } else {
            msg.setSeverity(FacesMessage.SEVERITY_ERROR);
            FacesContext.getCurrentInstance().addMessage(null, msg);
        }

        return null;
    }
    
    public String signTimesheet() { 	
    	try {
	        timesheet.setSubmitted(true); //Submits the timesheet
	        timesheet.setApproved(null); //reset approved status (in case timesheet as rejected)
	        
	        saveTimesheet();
	        isValid = sheetTotalsEqualForty();
	        
	        if(isValid == false) {
	        	timesheet.setSubmitted(false);
	        	saveTimesheet();
	        	return null;
	        }
    		
			//Setting up key generator
			KeyPairGenerator keyGen = KeyPairGenerator.getInstance("DSA", "SUN");
			SecureRandom random = SecureRandom.getInstance("SHA1PRNG", "SUN");
			keyGen.initialize(1024, random);
			
			//Generating a keypair
			KeyPair pair = keyGen.generateKeyPair();
			PrivateKey priv = pair.getPrivate();
			PublicKey pub = pair.getPublic();
			
			Signature dsa = Signature.getInstance("SHA1withDSA", "SUN"); //signature object to generate signature
			dsa.initSign(priv); //signing signature with private key

            if (timeService.getCurrentWeekEnd().equals(timesheet.getWeekEnding())) {
            	System.out.println("Entered if statement");
                Employee user = userController.getUser();
                timesheet = timeService.getCurrentTimesheet(user);
            }
			
//			Employee user = userController.getUser();
//            timesheet = timeService.getCurrentTimesheet(user);

			String data = timesheet.toString();
			System.out.println("Signing: " + data);

			byte[] dataBytes = new byte[1024]; //Creating a byte array to store the data
			dataBytes = data.getBytes(); //Convert the data from string to bytes
			
			dsa.update(dataBytes); //Update the signature object with the data
			
			byte[] realSig = dsa.sign(); //Create signature

			byte[] key = pub.getEncoded(); //Convert the public key into a byte array
			
			sigObject = new SignatureObject(realSig, key); //Create the signature object model

			sigObject.setId(timesheet.getId());
			signatureManager.persist(sigObject); //Persist the newly created model into the database
		} catch(Exception e) {
			logger.log(Level.ERROR, e.getMessage(), e);
			return null;
		} 

    	return "mypage";
    }
    
    public boolean verifyTimesheet() {
    	try {
		  		
			String data = timesheet.toString();
			System.out.println("Verifying: " + data);
			
			SignatureObject sigObject = signatureManager.find(timesheet.getId()); //Retrieve signature model

			byte[] encKey = sigObject.getPublicKey(); //Retrieve public key
			
			//Decode the public key
			X509EncodedKeySpec pubKeySpec = new X509EncodedKeySpec(encKey);
			KeyFactory keyFactory = KeyFactory.getInstance("DSA", "SUN");
			PublicKey pubKey = keyFactory.generatePublic(pubKeySpec);
			
			byte[] sigToVerify = sigObject.getSignature(); //Retrieve signature
			
			Signature sig = Signature.getInstance("SHA1withDSA", "SUN");
			sig.initVerify(pubKey); //Initialize verification with decoded public key			

			byte[] dataBytes = data.getBytes(); //Retrieve data
			sig.update(dataBytes); //Update signature with data

			return sig.verify(sigToVerify); //Verify whether signature is valid
			
		} catch (Exception e) {
			System.err.println("Caught exception " + e.toString());
		}
    	
    	return false;
    }
    
    /**
     * Returns false if the 'Row Total - (FLEX + OT) > 40'
     * 
     * @return          true if the total is valid
     */
    public boolean sheetTotalsLessThanForty() {
        // Ensure timesheet is not null
        if (timesheet != null) {
            double netTotal = timesheet.getTotal();
            double grossTotal = netTotal - (timesheet.getFlextime().doubleValue() 
                    + timesheet.getOvertime().doubleValue());

            if (grossTotal > 40.0) {
                FacesMessage msg = new FacesMessage(
                        "Total person-hours in week must be exactly equal to 40.00\n"
                                + "Where person-hours = Total - (FLEX + OT)");
                msg.setSeverity(FacesMessage.SEVERITY_ERROR);
                FacesContext.getCurrentInstance().addMessage(null, msg);
                return false;
            }
            return true;
        } else {
            // Return false if timesheet is null
            logger.info("sheetTotalsAreVald()::Timesheet is null");
            return false;
        }
    }
    
    /**

src/main/webapp/timesheets/_TimesheetTablePartial.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition>
		<h:form>
			<!-- timesheet summary -->
			<div class="row">
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading"><b>#{msgs.tsSummary}</b></div>
						<div class="panel-body">
							<dl class="dl-horizontal">
								<dt>#{msgs.tsOwner}</dt>
								<dd>
									#{timesheetController.timesheet.owner.firstName}
									#{timesheetController.timesheet.owner.lastName}
								</dd>
								<dt>#{msgs.weekEnding}</dt>
								<dd>#{timesheetController.timesheet.weekEnding}</dd>

								<dt>#{msgs.weekNo}</dt>
								<dd>#{timesheetController.timesheet.weekNumber}</dd>

								<dt>#{msgs.totalHours}</dt>
								<dd>#{timesheetController.timesheet.total}</dd>

								<dt>#{msgs.tsFlextime}</dt>
								<dd>#{timesheetController.timesheet.flextime}</dd>

								<dt>#{msgs.overtime}</dt>
								<dd>#{timesheetController.timesheet.overtime}</dd>

								<dt>#{msgs.tsValid}</dt>
								<dd>#{editTimesheetController.verifyTimesheet()} </dd>

								<dt>#{msgs.status}</dt>
								<dd class="#{(timesheetController.timesheet.approved == 'Rejected') ? 'text-danger' : ''}">
									#{timesheetController.timesheet.approved}
								</dd>
							</dl>
						</div>
					</div>
				</div>
			</div>

			<!-- timesheet table -->
			<div class="row">
				<div id="timesheetTable">
					<p:dataTable var="row" value="#{timesheetController.timesheet.timesheetRows}">
						<p:column headerText="#{msgs.project}">
							#{row.workPackage.project.id}
						</p:column>
						<p:column headerText="#{msgs.workPackage}">
							#{row.workPackage.packageNum}
						</p:column>
						<p:column headerText="#{msgs.total}" styleClass="hour-col">
							#{row.totalHours}
						</p:column>
						<p:column headerText="#{msgs.sun}" styleClass="hour-col">
							#{row.sundayHour}
						</p:column>
						<p:column headerText="#{msgs.sat}" styleClass="hour-col">
							#{row.saturdayHour}
						</p:column>
						<p:column headerText="#{msgs.mon}" styleClass="hour-col">
							#{row.mondayHour}
						</p:column>
						<p:column headerText="#{msgs.tue}" styleClass="hour-col">
							#{row.tuesdayHour}
						</p:column>
						<p:column headerText="#{msgs.wed}" styleClass="hour-col">
							#{row.wednesdayHour}
						</p:column>
						<p:column headerText="#{msgs.thu}" styleClass="hour-col">
							#{row.thursdayHour}
						</p:column>
						<p:column headerText="#{msgs.fri}" styleClass="hour-col">
							#{row.fridayHour}
						</p:column>
						<p:column headerText="#{msgs.notes}">
							#{row.notes}
						</p:column>
					</p:dataTable>
				</div>
			</div>
		</h:form>
	</ui:composition>
</h:body>
<!-- end of body -->
</html>

src/main/webapp/timesheets/pendingTimesheet.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">

		<ui:define name="windowTitle">#{msgs.pendingTimesheet}</ui:define>

		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="timesheet.css" />
		</ui:define>



		<ui:define name="content">
			<!-- change the value if using left menu -->
			<div class="col-md-12">

				<div class="container-fluid" id="content">

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">

							<div id="breadcrumb">
								<h:form>
									<ol class="breadcrumb">
										<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
										<li class="active">#{msgs.pendingTimesheet}</li>
									</ol>
								</h:form>
							</div>

							<div id="pageTitle">
								<h1>#{msgs.pendingTimesheet}</h1>
							</div>
							<ui:insert name="notificationArea">
								<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
							</ui:insert>
						</div>
					</div>

					<div class="row">
						<!-- displays info about previous timesheets of current user -->
						<div class="col-xs-12 col-sm-12 col-md-9">
							<h:form>
								<p:dataTable var="timesheet" value="#{timesheetController.pendingsSheets}">
									<p:column headerText="#{msgs.weekNo}">
										<h:outputText  class="paddingHalf" value="#{timesheet.weekNumber}" />
									</p:column>
									<p:column headerText="#{msgs.weekEnding}">
										<h:outputText class="paddingHalf" value="#{timesheet.weekEnding}" />
									</p:column>
									<p:column headerText="#{msgs.status}">
										<h:outputText value="#{timesheet.approved}" styleClass=" paddingHalf #{timesheet.approved == 'Rejected' ? 'text-danger' : ''}" />
									</p:column>
									<p:column>
										[ <h:commandLink value="#{msgs.view}" action="#{timesheetController.viewPendingTimesheet(timesheet)}" /> ]
										<ui:fragment rendered="#{timesheet.approved == 'Rejected'}">
											| [ <h:commandLink value="#{msgs.correct}"
															   action="#{editTimesheetController.fillSheetToCorrect(timesheet)}" /> ]
										</ui:fragment>
									</p:column>
								</p:dataTable>
							</h:form>
						</div>
						<!-- /col -->
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /col -->

		</ui:define>
		<!-- end of wrapper -->
	</ui:composition>
</h:body>
<!-- end of body -->
</html>

src/main/webapp/timesheets/pendingTimesheetTA.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title></title>
</h:head>
<h:body>	
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">
	<f:metadata>
		<f:event type="preRenderView" listener="#{userController.checkAuthorization}" />
		<f:attribute name="requiredRoles" value="Timesheet Approver" />
	</f:metadata>

		<ui:define name="windowTitle">#{msgs.approverPendingList}</ui:define>

		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="timesheet.css" />
		</ui:define>



		<ui:define name="content">
			<!-- change the value if using left menu -->
			<div class="col-md-12">

				<div class="container-fluid" id="content">

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">

							<div id="breadcrumb">
								<h:form>
									<ol class="breadcrumb">
										<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
										<li class="active">#{msgs.approverPendingList}</li>
									</ol>
								</h:form>
							</div>

							<div id="pageTitle">
								<h1>#{msgs.approverPendingList}</h1>
							</div>
							<ui:insert name="notificationArea">
								<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
							</ui:insert>
						</div>
					</div>

					<div class="row">
						<!-- displays info about previous timesheets of current user -->
						<div class="col-xs-12 col-sm-12 col-md-9">
							<h:form>
							<p:dataTable var="timesheet" value="#{timesheetController.tsApproverPendingList}">
								<p:column headerText="#{msgs.employee}">
									<h:outputText class="paddingHalf" value="#{timesheet.owner.firstName} #{timesheet.owner.lastName}" />
								</p:column>
								<p:column headerText="#{msgs.weekNo}">
									<h:outputText class="paddingHalf" value="#{timesheet.weekNumber}" />
								</p:column>
								<p:column headerText="#{msgs.weekEnding}">
									<h:outputText  class="paddingHalf" value="#{timesheet.weekEnding}" />
								</p:column>
								<p:column>
									<h:commandLink class="paddingHalf" value="#{msgs.review}" action="#{timesheetController.reviewTimesheet(timesheet)}" />
								</p:column>
							</p:dataTable>
							</h:form>
						</div>
						<!-- /col -->
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /col -->

		</ui:define>
		<!-- end of wrapper -->
	</ui:composition>
</h:body>
<!-- end of body -->
</html>

src/main/webapp/timesheets/previousTimesheet.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title></title>
</h:head>
<h:body>
	<ui:composition template="/templatesBootstrap/masterLayout.xhtml">

		<ui:define name="windowTitle">#{msgs.previousTimesheet}</ui:define>

		<ui:define name="additionalStyleSheets">
			<h:outputStylesheet library="css" name="timesheet.css" />
		</ui:define>



		<ui:define name="content">
			<!-- change the value if using left menu -->
			<div class="col-md-12">

				<div class="container-fluid" id="content">

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">

							<div id="breadcrumb">
								<h:form>
									<ol class="breadcrumb">
										<li><h:commandLink action="mypage" value="#{msgs.myPage}" /></li>
										<li class="active">#{msgs.previousTimesheet}</li>
									</ol>
								</h:form>
							</div>

							<div id="pageTitle">
								<h1>#{msgs.previousTimesheet}</h1>
							</div>
							<ui:insert name="notificationArea">
								<ui:include src="/templatesBootstrap/notificationArea.xhtml" />
							</ui:insert>
						</div>
					</div>

					<div class="row">
						<!-- displays info about previous timesheets of current user -->
						<div class="col-xs-12 col-sm-12 col-md-9">
							<h:form>
								<p:dataTable var="timesheet" value="#{timesheetController.previousSheets}">
									<p:column headerText="#{msgs.weekNo}">
										<h:outputText class="paddingHalf" value=" #{timesheet.weekNumber}" />
									</p:column>
									<p:column headerText="#{msgs.weekEnding}">
										<h:outputText  class="paddingHalf" value="#{timesheet.weekEnding}" />
									</p:column>
									<p:column>
										<h:commandLink class="paddingHalf" value="#{msgs.view}" action="#{timesheetController.viewTimesheet(timesheet)}" />
									</p:column>
								</p:dataTable>
							</h:form>
						</div>
						<!-- /col -->
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /col -->

		</ui:define>
		<!-- end of wrapper -->
	</ui:composition>
</h:body>
<!-- end of body -->
</html>